name: Citizeen_luk_up

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt, clippy, audit
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Clippy
      run: cargo clippy --all -- -D warnings
    - name: Run Rustfmt
      run: cargo fmt -- --check
    - name: Audit crates
      run: cargo audit
